auth0-domain: xxx.eu.auth0.com

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: xxx
            client-secret: xxx
            authorization-grant-type: authorization_code
            redirect-uri-template: '{baseUrl}/login/oauth2/code/auth0'
            client-name: auth0
            scope: openid profile
        provider:
          auth0:
            authorization-uri: https://${auth0-domain}/authorize
            token-uri: https://${auth0-domain}/oauth/token
            user-info-uri: https://${auth0-domain}/userinfo
            user-name-attribute: sub

logging:
  level:
    org.springframework.web: DEBUG
