spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri-template: '{baseUrl}/login/oauth2/code/auth0'
            client-name: auth0
            scope: openid profile
        provider:
          auth0:
            authorization-uri: https://${AUTH0_DOMAIN}/authorize
            token-uri: https://${AUTH0_DOMAIN}/oauth/token
            user-info-uri: https://${AUTH0_DOMAIN}/userinfo
            user-name-attribute: sub
